# Generated by Django 5.2.16 on 2026-07-14 09:04

import catalog.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_seed_fiberreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='applink',
            name='api_token',
            field=catalog.fields.EncryptedCharField(blank=True, editable=True, help_text='Stesso valore di INTERNAL_API_TOKEN nel .env di quella app. Cifrato a riposo.', null=True),
        ),
        migrations.AddField(
            model_name='applink',
            name='internal_base_url',
            field=models.URLField(blank=True, help_text="Es. https://127.0.0.1:8444 — l'app chiamata via loopback, non l'URL pubblico sopra. Lasciare vuoto se questa app non espone la gestione utenti.", verbose_name='URL base API interna'),
        ),
    ]
