# Generated by Django 5.2.16 on 2026-08-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_seed_preventivi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applink',
            options={'ordering': ['categoria', 'order', 'name']},
        ),
        migrations.AddField(
            model_name='applink',
            name='categoria',
            field=models.CharField(choices=[('interna', 'Applicazioni interne'), ('cliente', 'Applicazioni clienti')], default='interna', help_text='Sezione del launcher in cui compare la card.', max_length=20),
        ),
    ]
