# Generated by Django 5.2.16 on 2026-08-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_applink_options_applink_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applink',
            options={'ordering': ['-categoria', 'order', 'name']},
        ),
        migrations.AddField(
            model_name='applink',
            name='dev_status',
            field=models.CharField(choices=[('produzione', 'In produzione'), ('beta', 'Beta'), ('sviluppo', 'In sviluppo'), ('manutenzione', 'In manutenzione')], default='produzione', help_text='Mostrato come pallino colorato sulla card.', max_length=20),
        ),
    ]
