# Generated by Django 5.2.16 on 2026-08-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_applink_dev_status_to_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='applink',
            name='internal_ca_cert',
            field=models.CharField(blank=True, help_text="Percorso del certificato usato per verificare la connessione a internal_base_url (es. /etc/ssl/mkremote/selfsigned.crt), invece di disattivare la verifica TLS (RedFlag id 87). Se vuoto, la verifica standard si applica e fallirà per i certificati self-signed dell'IP del VPS.", max_length=255, verbose_name='Certificato TLS (pinning)'),
        ),
    ]
