# Generated by Django 5.2.16 on 2026-07-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clienti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='aliquota_iva_predefinita',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='codice_fiscale',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='codice_sdi',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='cliente',
            name='iban',
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AddField(
            model_name='cliente',
            name='indirizzo_spedizione',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cliente',
            name='note_indirizzo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cliente',
            name='paese',
            field=models.CharField(blank=True, default='Italia', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='pec',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Indirizzo PEC'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='referente',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sconto_predefinito',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='termini_pagamento',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='citta',
            field=models.CharField(blank=True, max_length=100, verbose_name='Comune'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Indirizzo e-mail'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='piva',
            field=models.CharField(blank=True, max_length=20, verbose_name='P.IVA/TAX ID'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='provincia',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ragione_sociale',
            field=models.CharField(max_length=255, verbose_name='Denominazione'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
